--------------------------------------------------------
--  だ橾檜 儅撩脾 - 錯蹂橾-11錯-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARDDB
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BOARDDB" 
   (	"BID" NUMBER(4,0), 
	"BNAME" VARCHAR2(20 BYTE), 
	"BTITLE" VARCHAR2(100 BYTE), 
	"BCONTENT" VARCHAR2(300 BYTE), 
	"BDATE" DATE DEFAULT sysdate, 
	"BHIT" NUMBER(4,0) DEFAULT 0, 
	"BGROUP" NUMBER(4,0), 
	"BSTEP" NUMBER(4,0), 
	"BINDENT" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.BOARDDB
SET DEFINE OFF;
Insert into SCOTT.BOARDDB (BID,BNAME,BTITLE,BCONTENT,BDATE,BHIT,BGROUP,BSTEP,BINDENT) values (5,'zzzz','zzz','zzzz',to_date('20/11/06','RR/MM/DD'),7,5,0,0);
Insert into SCOTT.BOARDDB (BID,BNAME,BTITLE,BCONTENT,BDATE,BHIT,BGROUP,BSTEP,BINDENT) values (3,'六六ggg','[RE] 六六','六六',to_date('20/11/05','RR/MM/DD'),1,2,1,1);
Insert into SCOTT.BOARDDB (BID,BNAME,BTITLE,BCONTENT,BDATE,BHIT,BGROUP,BSTEP,BINDENT) values (2,'六六','六六ggg','六六',to_date('20/11/05','RR/MM/DD'),4,2,0,0);
Insert into SCOTT.BOARDDB (BID,BNAME,BTITLE,BCONTENT,BDATE,BHIT,BGROUP,BSTEP,BINDENT) values (4,'寰喟','冗冗','冗冗',to_date('20/11/06','RR/MM/DD'),5,4,0,0);
--------------------------------------------------------
--  DDL for Index SYS_C0011229
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011229" ON "SCOTT"."BOARDDB" ("BID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARDDB
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARDDB" ADD PRIMARY KEY ("BID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
